version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 90.0

  - !LearningRateModifier
    start_epoch: 0.0
    lr_class: MultiStepLR
    lr_kwargs:
      milestones: [30, 60]
      gamma: 0.1
    init_lr: 0.1
