version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 100.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.005

  - !LearningRateModifier
    start_epoch: 40.0
    lr_class: ExponentialLR
    lr_kwargs:
      gamma: 0.925
    init_lr: 0.005

  - !GradualKSModifier
    params:
      - sections.0.0.conv1.weight
      - sections.0.0.conv2.weight
      - sections.0.0.conv3.weight
      - sections.0.0.identity.conv.weight
      - sections.0.1.conv1.weight
      - sections.0.1.conv2.weight
      - sections.0.1.conv3.weight
      - sections.0.2.conv1.weight
      - sections.0.2.conv2.weight
      - sections.0.2.conv3.weight
      - sections.1.0.conv1.weight
      - sections.1.0.conv2.weight
      - sections.1.0.conv3.weight
      - sections.1.0.identity.conv.weight
      - sections.1.1.conv1.weight
      - sections.1.1.conv2.weight
      - sections.1.1.conv3.weight
      - sections.1.2.conv1.weight
      - sections.1.2.conv2.weight
      - sections.1.2.conv3.weight
      - sections.1.3.conv1.weight
      - sections.1.3.conv2.weight
      - sections.1.3.conv3.weight
      - sections.2.0.conv1.weight
      - sections.2.0.conv2.weight
      - sections.2.0.conv3.weight
      - sections.2.0.identity.conv.weight
      - sections.2.1.conv1.weight
      - sections.2.1.conv2.weight
      - sections.2.1.conv3.weight
      - sections.2.2.conv1.weight
      - sections.2.2.conv2.weight
      - sections.2.2.conv3.weight
      - sections.2.3.conv1.weight
      - sections.2.3.conv2.weight
      - sections.2.3.conv3.weight
      - sections.2.4.conv1.weight
      - sections.2.4.conv2.weight
      - sections.2.4.conv3.weight
      - sections.2.5.conv1.weight
      - sections.2.5.conv2.weight
      - sections.2.5.conv3.weight
      - sections.3.0.conv1.weight
      - sections.3.0.conv2.weight
      - sections.3.0.conv3.weight
      - sections.3.0.identity.conv.weight
      - sections.3.1.conv1.weight
      - sections.3.1.conv2.weight
      - sections.3.1.conv3.weight
      - sections.3.2.conv1.weight
      - sections.3.2.conv2.weight
      - sections.3.2.conv3.weight
    init_sparsity: 0.05
    final_sparsity: 0.875
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.25
