version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 90.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.005

  - !LearningRateModifier
    start_epoch: 40.0
    lr_class: CosineAnnealingWarmRestarts
    lr_kwargs:
      lr_min: 0.00005
      cycle_epochs: 50
    init_lr: 0.005

  - !GradualKSModifier
    params:
      - sections.1.0.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.85
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.1.1.conv.weight
      - sections.2.0.conv.weight
      - sections.3.0.conv.weight
      - sections.4.0.conv.weight
      - sections.4.1.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.9
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.2.1.conv.weight
      - sections.2.2.conv.weight
      - sections.3.1.conv.weight
      - sections.3.2.conv.weight
      - sections.4.2.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.95
    start_epoch: 1.0
    end_epoch: 32.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - classifier.mlp.0.weight
      - classifier.mlp.3.weight
    init_sparsity: 0.05
    final_sparsity: 0.975
    start_epoch: 6.0
    end_epoch: 40.0
    update_frequency: 0.5
