version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 90.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.005

  - !LearningRateModifier
    start_epoch: 40.0
    lr_class: CosineAnnealingWarmRestarts
    lr_kwargs:
      lr_min: 0.00005
      cycle_epochs: 50
    init_lr: 0.005

  - !GradualKSModifier
    params:
      - sections.1.1.expand.conv.weight
      - sections.1.1.compress.conv.weight
      - sections.2.0.expand.conv.weight
      - sections.2.0.compress.conv.weight
      - sections.3.0.expand.conv.weight
      - sections.3.0.compress.conv.weight
      - classifier.fc.weight
    init_sparsity: 0.05
    final_sparsity: 0.6
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.2.1.expand.conv.weight
      - sections.2.1.compress.conv.weight
      - sections.2.2.expand.conv.weight
      - sections.2.2.compress.conv.weight
      - sections.3.1.expand.conv.weight
      - sections.3.1.compress.conv.weight
      - sections.3.2.expand.conv.weight
      - sections.3.3.expand.conv.weight
      - sections.4.0.expand.conv.weight
      - sections.4.0.compress.conv.weight
      - sections.5.0.expand.conv.weight
      - sections.5.0.compress.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.7
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.3.2.compress.conv.weight
      - sections.3.3.compress.conv.weight
      - sections.4.1.expand.conv.weight
      - sections.4.1.compress.conv.weight
      - sections.4.2.expand.conv.weight
      - sections.4.2.compress.conv.weight
      - sections.5.1.expand.conv.weight
      - sections.5.1.compress.conv.weight
      - sections.5.2.expand.conv.weight
      - sections.5.2.compress.conv.weight
      - sections.6.0.expand.conv.weight
      - sections.6.0.compress.conv.weight
      - feat_extraction.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.8
    start_epoch: 1.0
    end_epoch: 36.0
    update_frequency: 0.5
