version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 140.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.005

  - !LearningRateModifier
    start_epoch: 65.0
    lr_class: CosineAnnealingWarmRestarts
    lr_kwargs:
      lr_min: 0.00005
      cycle_epochs: 50
    init_lr: 0.005

  - !GradualKSModifier
    params:
      - sections.0.0.point.conv.weight
      - sections.1.0.point.conv.weight
      - sections.1.1.point.conv.weight
      - sections.2.0.point.conv.weight
      - classifier.fc.1.weight
    init_sparsity: 0.05
    final_sparsity: 0.6
    start_epoch: 1.0
    end_epoch: 60.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.2.1.point.conv.weight
      - sections.3.0.point.conv.weight
      - sections.3.1.point.conv.weight
      - sections.3.5.point.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.725
    start_epoch: 1.0
    end_epoch: 60.0
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - sections.3.2.point.conv.weight
      - sections.3.3.point.conv.weight
      - sections.3.4.point.conv.weight
      - sections.4.0.point.conv.weight
      - sections.4.1.point.conv.weight
    init_sparsity: 0.05
    final_sparsity: 0.85
    start_epoch: 1.0
    end_epoch: 60.0
    update_frequency: 0.5
