version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 60.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.001

  - !LearningRateModifier
    start_epoch: 0.0
    lr_class: MultiStepLR
    lr_kwargs:
      milestones: [44, 53]
      gamma: 0.1
    init_lr: 0.001

  - !GradualKSModifier
    params:
      - feature_extractor.1.0.conv1.weight
      - feature_extractor.1.0.conv3.weight
      - feature_extractor.1.0.identity.conv.weight
      - feature_extractor.1.1.conv1.weight
      - feature_extractor.1.1.conv2.weight
      - feature_extractor.1.1.conv3.weight
      - feature_extractor.1.2.conv1.weight
      - feature_extractor.1.2.conv2.weight
      - feature_extractor.1.2.conv3.weight
      - feature_extractor.2.0.conv1.weight
      - feature_extractor.2.0.conv2.weight
      - feature_extractor.2.0.conv3.weight
      - feature_extractor.2.2.conv3.weight
      - feature_extractor.2.3.conv1.weight
      - feature_extractor.2.3.conv3.weight
      - feature_extractor.3.0.conv1.weight
      - head.0.conv1.weight
    init_sparsity: 0.05
    final_sparsity: 0.8
    start_epoch: 2
    end_epoch: 42
    update_frequency: 40

  - !GradualKSModifier
    params:
      - feature_extractor.1.0.conv2.weight
      - feature_extractor.2.0.identity.conv.weight
      - feature_extractor.2.1.conv1.weight
      - feature_extractor.2.1.conv2.weight
      - feature_extractor.2.1.conv3.weight
      - feature_extractor.2.2.conv1.weight
      - feature_extractor.2.2.conv2.weight
      - feature_extractor.2.3.conv2.weight
      - feature_extractor.3.0.conv3.weight
      - feature_extractor.3.1.conv1.weight
      - feature_extractor.3.1.conv3.weight
      - feature_extractor.3.2.conv1.weight
      - feature_extractor.3.2.conv3.weight
      - feature_extractor.3.3.conv1.weight
      - feature_extractor.3.3.conv3.weight
      - feature_extractor.3.4.conv1.weight
      - feature_extractor.3.4.conv3.weight
      - feature_extractor.3.5.conv1.weight
      - feature_extractor.3.5.conv3.weight
      - head.0.conv2.weight
      - head.1.conv2.weight
      - head.2.conv2.weight
      - predictor.location_predictor.3.weight
      - predictor.confidence_predictor.3.weight
      - head.3.conv2.weight
      - predictor.location_predictor.4.weight
      - predictor.confidence_predictor.4.weight
      - head.4.conv2.weight
    init_sparsity: 0.05
    final_sparsity: 0.85
    start_epoch: 2
    end_epoch: 42
    update_frequency: 0.5

  - !GradualKSModifier
    params:
      - feature_extractor.3.0.identity.conv.weight
      - feature_extractor.3.0.conv2.weight
      - feature_extractor.3.1.conv2.weight
      - feature_extractor.3.2.conv2.weight
      - feature_extractor.3.3.conv2.weight
      - feature_extractor.3.4.conv2.weight
      - feature_extractor.3.5.conv2.weight
      - predictor.location_predictor.0.weight
      - predictor.confidence_predictor.0.weight
      - predictor.confidence_predictor.1.weight
      - predictor.location_predictor.1.weight
      - predictor.location_predictor.2.weight
      - predictor.confidence_predictor.2.weight
    init_sparsity: 0.05
    final_sparsity: 0.9
    start_epoch: 2
    end_epoch: 42
    update_frequency: 40
