version: 1.1.0

modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 10.0

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: 0.0001

  - !QuantizationModifier
    start_epoch: 0.0
    disable_quantization_observer_epoch: 7.0
    freeze_bn_stats_epoch: 6.0

  # Preserve sparsity when quantizing sparse models
  - !ConstantKSModifier
    start_epoch: 0.0
    params: __ALL__
