name: Build release wheel

on:
  push:
    branches:
      - 'release/*'

  workflow_dispatch:
    inputs:
      gitref:
        description: "git tag, commit or branch name for the release"
        type: string
        required: true
        default: 'release/1.8'

jobs:
  build-release-wheel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        run: |
          pip install uv
          uv sync
          
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.gitref }}
      
      - name: Build PyPi Wheel
        id: build
        run: |
          uv build

      - name: Set Env
        run: |
          uv venv venv
          source venv/bin/activate

      - name: upload whl
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: "wheel-sparseml"
          path: ${{ steps.build.outputs.whlname }}
          retention-days: 7

      - name: upload tar.gz
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: "tar-sparseml"
          path: ${{ steps.build.outputs.tarname }}
          retention-days: 7
