name: Integrations Testing Post-Merge
on: 
  push:
    branches:
      - main
      - 'release/*'

jobs:
  test-setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git branch --show-current
      - name: Get current branch
        id: get-branch
        run: >
          (git branch --show-current | grep -E "release/")
          && echo "::set-output name=branch::$(git branch --show-current)"
          || echo "::set-output name=branch::main"

  integrations-tests:
    runs-on: ubuntu-22.04
    needs: test-setup
    env:
      SPARSEZOO_TEST_MODE: "true"
      SPARSEML_TEST_CADENCE: "commit"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install uv
        run: |
          pip install uv
          uv sync
      - name: "⚙️ Install sparsezoo dependencies"
        run: uv pip install setuptools sparsezoo/
      - name: "Clean sparsezoo directory"
        run: rm -r sparsezoo/
      - uses: actions/checkout@v4
        with:
          repository: "neuralmagic/compressed-tensors"
          path: "compressed-tensors"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install compressed-tensors dependencies"
        run: uv pip install setuptools compressed-tensors/
      - name: "Clean compressed-tensors directory"
        run: rm -r compressed-tensors/
      - name: "⚙️ Install dependencies"
        run: uv sync --extra dev --extra torchvision --extra deepsparse --extra onnxruntime --extra transformers --extra yolov5
      - name: "🔬 Running integrations tests (cadence: commit}})"
        run: uv run make testinteg TARGETS=yolov5,transformers,image_classification
