name: Quality Checks
on: 
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'
jobs:
  quality-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install uv
        run: |
          pip install uv
          uv sync
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: "neuralmagic/sparsezoo"
          path: "sparsezoo"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: "⚙️ Install sparsezoo dependencies"
        run: uv pip install sparsezoo/
      - name: "Clean sparsezoo directory"
        run: rm -r sparsezoo/
      - name: "⚙️ Install dependencies"
        run: uv sync --extra dev
      - name: "🧹 Running quality checks"
        run: uv run make quality
