name: Run Weekly tests
on:
  schedule:
    - cron: '0 20 * * 0' # Run weekly on Sunday at 8 PM UTC
  workflow_dispatch:
    inputs:
      run-gpu-tests:
        description: 'Run GPU tests'
        required: false
        default: true # Default to true for weekly, more intensive tests
        type: boolean
jobs:
  run-weekly-tests:
    if: ${{ github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-gpu-tests == true) }}
    runs-on: k8s-mle-gpu-12-vcpu-225GB-ram-2-a6000-48G
    env:
      CADENCE: "weekly"
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_FILES_HOST:  ${{ secrets.CLEARML_FILES_HOST }}
      CLEARML_API_SECRET_KEY:  ${{ secrets.CLEARML_API_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "neuralmagic/compressed-tensors"
          path: "compressed-tensors"
          # Assuming 'main' is the correct default if test-setup is not a dependency here
          ref: main
      - name: Install uv
        run: |
          pip install uv
          uv sync
      - name: "⚙️ Install compressed-tensors dependencies"
        run: uv pip install setuptools compressed-tensors/
      - name: "Clean compressed-tensors directory"
        run: rm -r compressed-tensors/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "⚙️ Install dependencies"
        run: uv sync --extra dev --extra onnxruntime --extra torch --extra torchvision --extra transformers
      - name: Run oneshot tests
        run: |
          uv run pytest tests/sparseml/transformers/obcq -m integration
      - name: Run finetune tests
        if: always()
        run: |
          uv run pytest tests/sparseml/transformers/finetune -m integration
