name: Run Weekly tests
on:
  schedule:
    - cron: '0 20 * * 0'
  workflow_dispatch:
jobs:
  run-weekly-tests:
    runs-on: k8s-mle-gpu-12-vcpu-225GB-ram-2-a6000-48G
    env:
      CADENCE: "weekly"
      CLEARML_WEB_HOST: ${{ secrets.CLEARML_WEB_HOST }}
      CLEARML_API_HOST: ${{ secrets.CLEARML_API_HOST }}
      CLEARML_API_ACCESS_KEY: ${{ secrets.CLEARML_API_ACCESS_KEY }}
      CLEARML_FILES_HOST:  ${{ secrets.CLEARML_FILES_HOST }}
      CLEARML_API_SECRET_KEY:  ${{ secrets.CLEARML_API_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: "neuralmagic/compressed-tensors"
          path: "compressed-tensors"
          ref: ${{needs.test-setup.outputs.branch}}
      - name: Install uv
        run: pip install uv
      - name: "⚙️ Install compressed-tensors dependencies"
        run: uv pip install setuptools compressed-tensors/
      - name: "Clean compressed-tensors directory"
        run: rm -r compressed-tensors/
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: "⚙️ Install dependencies"
        run: uv sync --extra dev --extra onnxruntime --extra torch --extra torchvision --extra transformers
      - name: Run oneshot tests
        run: |
          uv run pytest tests/sparseml/transformers/obcq -m integration
      - name: Run finetune tests
        if: always()
        run: |
          uv run pytest tests/sparseml/transformers/finetune -m integration
